version: '3.7'

services:
    app:
        container_name: go-api-app-container
        image: go-api/go-image
        build:
            args:
                USER: "localdev"
                UID: "${UID:-1000}"
            context: ../../
            target: dev
            dockerfile: docker/local/Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db
            - redis
        volumes:
            - ../../:/app
        ports:
            - "4000:4000"
        networks:
            - go_api_local_network

    db:
        image: postgres:13
        container_name: go-api-db-container
        restart: always
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - go_api_db_data:/var/lib/postgresql/data
        networks:
            - go_api_local_network

    redis:
        image: redis:latest
        container_name: go-api-redis-container
        command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD}'
        volumes:
            - go_api_redis_data:/var/lib/redis/data
        ports:
            - "6379:6379"
        networks:
            - go_api_local_network

networks:
    go_api_local_network:

volumes:
    go_api_db_data:
    go_api_redis_data:
